CC = gcc
LIBS = -pthread -lrt

all: program0.c program1.c program2.c program3.c
	$(CC) -o program0 program0.c $(LIBS)
	$(CC) -o program1 program1.c $(LIBS)
	$(CC) -o program2 program2.c $(LIBS)
	$(CC) -o program3 program3.c $(LIBS) 
